#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-cayman
title: Workshop on Complex Geometry in Osaka 2024
description: 13th--15th March 2024.
# theme: jekyll-theme-cayman